//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class airticket
    {
        public int id { get; set; }
        public Nullable<int> flight_id { get; set; }
        public int callout_id { get; set; }
        public Nullable<int> person_id { get; set; }
        public int departure_at { get; set; }
        public int created_at { get; set; }
        public int payment { get; set; }
        public int is_baggage { get; set; }
        public int is_baby { get; set; }
    
        public virtual flight flight { get; set; }
        public virtual callout callout { get; set; }
        public virtual person person { get; set; }
    }
}
