//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class airticket
    {
        public int id { get; set; }
        public Nullable<int> flight_id { get; set; }
        public int callout_id { get; set; }
        public Nullable<int> person_id { get; set; }
        public int departure_at { get; set; }
        public int created_at { get; set; }
        public int payment { get; set; }
        public int is_baggage { get; set; }
        public int is_baby { get; set; }
    
        public virtual flight flight { get; set; }
        public virtual callout callout { get; set; }
        public virtual person person { get; set; }
    }
}
