//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class callout_order
    {
        public int id { get; set; }
        public int callout_id { get; set; }
        public int person_id { get; set; }
        public int employee_id { get; set; }
        public int created_at { get; set; }
        public int payment { get; set; }
        public Nullable<int> payment_at { get; set; }
        public int is_discount { get; set; }
        public Nullable<int> canceling_at { get; set; }
        public string status { get; set; }
    
        public virtual callout callout { get; set; }
        public virtual person person { get; set; }
        public virtual employee employee { get; set; }
    }
}
