//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.callout_order = new HashSet<callout_order>();
        }
    
        public int id { get; set; }
        public int person_id { get; set; }
        public string position { get; set; }
        public int created_at { get; set; }
        public Nullable<int> salary { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string session { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<callout_order> callout_order { get; set; }
        public virtual person person { get; set; }
    }
}
