//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class excursion_order
    {
        public int id { get; set; }
        public int excursion_id { get; set; }
        public int callout_id { get; set; }
        public int payment { get; set; }
        public string starting_address { get; set; }
        public int starting_at { get; set; }
        public int is_baby { get; set; }
        public int is_privilege { get; set; }
        public int is_custom { get; set; }
        public Nullable<int> bus_place_number { get; set; }
        public int created_at { get; set; }
    
        public virtual callout callout { get; set; }
        public virtual excursion excursion { get; set; }
    }
}
