//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotel()
        {
            this.hotel_service = new HashSet<hotel_service>();
            this.rooms = new HashSet<room>();
        }
    
        public int id { get; set; }
        public Nullable<int> tour_id { get; set; }
        public int city_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int stars_number { get; set; }
        public Nullable<int> distance_to_beach { get; set; }
        public Nullable<int> food_id { get; set; }
    
        public virtual city city { get; set; }
        public virtual food food { get; set; }
        public virtual tour tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotel_service> hotel_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room> rooms { get; set; }
    }
}
