//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_service_order
    {
        public int id { get; set; }
        public int hotel_service_id { get; set; }
        public int callout_id { get; set; }
        public int duration { get; set; }
        public Nullable<int> room_id { get; set; }
        public int payment { get; set; }
        public int provision_at { get; set; }
    
        public virtual callout callout { get; set; }
        public virtual hotel_service hotel_service { get; set; }
        public virtual room room { get; set; }
    }
}
