//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_service_order
    {
        public int id { get; set; }
        public int hotel_service_id { get; set; }
        public int callout_id { get; set; }
        public int duration { get; set; }
        public Nullable<int> room_id { get; set; }
        public int payment { get; set; }
        public int provision_at { get; set; }
        public int created_at { get; set; }
    
        public virtual callout callout { get; set; }
        public virtual hotel_service hotel_service { get; set; }
        public virtual room room { get; set; }
    }
}
